[[redirects]]
from = "/*"
to = "index.html"
status = 200

[build]
  command = "npm run build"
  publish = ".next"  # Replace "out" with your actual build output directory if different


[[plugins]]
  package = "@netlify/plugin-nextjs"
